name: Run builds and deploy/create release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build-linux-windows:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore ./src/tui/dinfo.tui.csproj

            # --- Self-Contained build ---
            - name: Publish Self-Contained Linux Package
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r linux-x64 \
                    --self-contained true \
                    /p:PublishSingleFile=false \
                    -o publish/self-contained/linux-x64

                  mv publish/self-contained/linux-x64/dinfo \
                  dinfo-linux-x64-self-contained

            - name: Publish Self-Contained Windows Package
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r win-x64 \
                    --self-contained true \
                    /p:PublishSingleFile=false \
                    -o publish/self-contained/win-x64

                  mv publish/self-contained/win-x64/dinfo.exe \
                  dinfo-win-x64-self-contained.exe

            - name: Upload Linux Artifacts
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: dinfo-linux
                  path: dinfo-linux-x64-self-contained

            - name: Upload Windows Artifacts
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: dinfo-win
                  path: dinfo-win-x64-self-contained.exe

            - name: Move NSI Script from release folder to root
              run: mv -v release/build-installer.nsi .

            - name: Upload NSI Script from repo
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: nsi-script
                  path: build-installer.nsi

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release-linux:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: build-linux-windows
        steps:
            - name: Download build
              uses: actions/download-artifact@v4.3.0
              with:
                  name: dinfo-linux

            # --- Upload binaries ---
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dinfo-linux-x64-self-contained
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release-windows:
        runs-on: windows-latest
        needs:
            - build-linux-windows
        permissions:
            contents: write
        steps:
            - name: Download build
              uses: actions/download-artifact@v4.3.0
              with:
                  name: dinfo-win

            - name: Copy program to dinfo file
              run: cp -v dinfo-win-x64-self-contained.exe dinfo.exe

            - name: Download NSI Script
              uses: actions/download-artifact@v5.0.0
              with:
                  name: nsi-script

            - name: Download and install NSIS
              run: wget "https://downloads.sourceforge.net/project/nsis/NSIS%203/3.11/nsis-3.11-setup.exe?ts=gAAAAABo5_2iGI_0gVEVZyxmYxQNTZ24mS4-CRzXAnDTotb8QRLRCaZL57yq2VQZA8Ryh8t-bSQGDNTe-ukRygoGFIUgzI8oBw%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnsis%2Ffiles%2FNSIS%25203%2F3.11%2Fnsis-3.11-setup.exe%2Fdownload%3Fuse_mirror%3Dnetix%26download" && ./nsis-3.11-setup.exe /S

            - name: Download and install NSIS EnVar Plugin
              run: wget "https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip" && tar xvf EnVar_plugin.zip && mv -v EnVar_Plugin/Plugins/* "C:\Program Files (x86)\NSIS\Plugins\"

            - name: Build installer
              uses: joncloud/makensis-action@v5.0
              with:
                  script-file: "build-installer.nsi"

            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dinfo-win-x64-self-contained.exe
                      win-installer.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
