name: Run builds and deploy/create release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore ./src/tui/dinfo.tui.csproj

            # --- Self-Contained build ---
            - name: Publish Self-Contained
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r linux-x64 \
                    --self-contained true \
                    /p:PublishSingleFile=false \
                    -o publish/self-contained/linux-x64

                  mv publish/self-contained/linux-x64/dinfo \
                  publish/self-contained/linux-x64/dinfo-linux-x64-self-contained
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4.6.2
              with:
                name: dinfo-linux
                path: publish/self-contained/linux-x64/dinfo-linux-x64-self-contained
    release-linux:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download build
              uses: actions/download-artifact@v5.0.0
              with:
                  name: dinfo-linux
              
            # --- Create GitHub Release ---
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # --- Upload binaries ---
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dinfo-linux-x64-self-contained
              env:

                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
