name: Release Zip Linux

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore ./src/tui/dinfo.tui.csproj

            # --- Self-Contained build ---
            - name: Publish Self-Contained
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r linux-x64 \
                    --self-contained true \
                    /p:PublishSingleFile=false \
                    -o publish/self-contained/linux-x64

                  mv publish/self-contained/linux-x64/dinfo \
                  publish/self-contained/linux-x64/dinfo-linux-x64-self-contained

            # --- Create zip ---
            - name: Create zip
              run: |
                  zip -r publish/self-contained/dinfo-linux-x64-self-contained.zip \
                  publish/self-contained/linux-x64/*

            # --- Create GitHub Release ---
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # --- Upload binaries ---
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      publish/self-contained/dinfo-linux-x64-self-contained.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}