name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                runtime: [linux-x64, win-x64, osx-x64]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore ./src/tui/dinfo.tui.csproj

            # --- Self-contained build ---
            - name: Publish Self-contained
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r ${{ matrix.runtime }} \
                    --self-contained true \
                    /p:PublishSingleFile=true \
                    -o publish/self-contained/${{ matrix.runtime }}

                  if [[ "${{ matrix.runtime }}" == "win-x64" ]]; then
                    mv publish/self-contained/${{ matrix.runtime }}/dinfo.exe publish/self-contained/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-self-contained.exe
                  else
                    mv publish/self-contained/${{ matrix.runtime }}/dinfo publish/self-contained/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-self-contained
                  fi

            # --- Framework-dependent build ---
            - name: Publish Framework-dependent
              run: |
                  dotnet publish ./src/tui/dinfo.tui.csproj \
                    -c Release \
                    -r ${{ matrix.runtime }} \
                    --self-contained false \
                    -o publish/framework-dependent/${{ matrix.runtime }}

                  if [[ "${{ matrix.runtime }}" == "win-x64" ]]; then
                    mv publish/framework-dependent/${{ matrix.runtime }}/dinfo.exe publish/framework-dependent/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-framework-dependent.exe
                  else
                    mv publish/framework-dependent/${{ matrix.runtime }}/dinfo publish/framework-dependent/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-framework-dependent
                  fi

            # --- Create GitHub Release ---
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # --- Upload binaries ---
            - name: Upload Release Assets
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      publish/self-contained/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-self-contained*
                      publish/framework-dependent/${{ matrix.runtime }}/dinfo-${{ matrix.runtime }}-framework-dependent*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
